### ISSUE TITLE
Allow adding open page

### ISSUE THREAD

**Issue by sotakal** [HipsterBrown/send-to-todoist#4]
Cool little minimalist extension but I wish I could right-click a page anywhere and send that page to Todoist, just as I can do with hyperlinks - would you consider adding support for this use case?

**Comment by HipsterBrown** [comment]
Sure! Thanks for creating an issue. Would you expect that item in Todoist to just contain the URL of the page?

**Comment by HipsterBrown** [comment]
@sotakal This has been shipped under version 1.6.0. Thanks again for letting me know about the feature!

**Comment by sotakal** [comment]
Wow, you were too fast! Amazing, thank you. That said, would it be possible to not only add the URL, but also include the page title as the URL title? Markdown-style linking should work in Todoist, i.e. `[page title goes here](url goes here)`

For example, for this page, the URL would not be only:
`https://github.com/HipsterBrown/send-to-todoist/issues/4`
but
`[Allow adding open page · Issue #4 · HipsterBrown/send-to-todoist](https://github.com/HipsterBrown/send-to-todoist/issues/4)`

Edit: I'm requesting this because some sites may not be available publicly and Todoist can't parse the title from the URL (which is what happens by default for public sites).

**Comment by HipsterBrown** [comment]
@sotakal Done! Version 1.6.1 has been published with this format. That's a good note about private pages not being parsed by Todoist. 👍

**Comment by sotakal** [comment]
Truly amazing, Nick, thanks so much! Deleting the official extension right away!
