### ISSUE TITLE
Extension context menu does not work after browser restart

### ISSUE THREAD

**Issue by sotakal** [HipsterBrown/send-to-todoist#5]
Sorry to report another issue - after I restart Firefox (85.0.2, Windows 10), the extension behaves as if it weren't configured - the context menus are not shown. I have to visit the extension configuration and interact with the text box where the API key is saved - after I enter an extra character, then remove it, the extension says "API key saved" and the context menus re-appear.

**Comment by HipsterBrown** [comment]
@sotakal Thanks for creating an issue. I'm aware of this one and have been investigating a fix. This update may take longer than the last.

**Comment by HipsterBrown** [comment]
@sotakal Ok I released version 1.6.2 that listens for startup and installed events in order to set up the context menus. 🤞 Hopefully that fixes it, not sure of a great way to test it.
