### ISSUE TITLE
Allow refreshing projects

### ISSUE THREAD

**Issue by sotakal** [HipsterBrown/send-to-todoist#6]
Would be great to have a "sync" button that would allow refreshing the project list when needed (e.g. when I create new projects, or rename projects and want to start working with the extension right away.

**Comment by HipsterBrown** [comment]
Done! Version 1.8.0 is out with a sync button and project ordering using the "order" key from the API. 

<img width="290" alt="Screen Shot 2021-02-26 at 11 40 20 PM" src="https://user-images.githubusercontent.com/3051193/109375819-a5a97480-788d-11eb-9c49-0757c519c732.png">
