### ISSUE TITLE
List projects in Todoist order

### ISSUE THREAD

**Issue by sotakal** [HipsterBrown/send-to-todoist#7]
Today the projects seem to be ordered by date created, or perhaps the project ids. I would expect to see them in the same order as they are in Todoist - to be more clear:

**Today I see:** (because I created child projects later, and Project 3-1 as the latest)
Project 1
Project 2
Project 3
Project 1-1
Project 1-2
Project 3-2
Project 3-3
Project 3-1

**What I would expect:**
Project 1
Project 1-1
Project 1-2
Project 2
Project 3
Project 3-1
Project 3-2
Project 3-3

**Comment by HipsterBrown** [comment]
Done! Version 1.8.0 is out with a sync button and project ordering using the "order" key from the API.

**Comment by sotakal** [comment]
A-mazing. Thanks so much!
